// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "adeisagopher",
            "url": "https://github.com/adeisagopher",
            "email": "adeisagopher@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/quote/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "get a quote by ID.",
                "operationId": "get-quote-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "quote ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "arrays"
                        }
                    }
                }
            }
        },
        "/quotes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "return all quotes stored in the database.",
                "operationId": "get-all-quotes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "arrays"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "quotesmonger.onrender.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Quotesmonger API",
	Description:      "A simple quotes API with multiple categories written in GO.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
